### ISSUE TITLE
Invalidation tracking

### ISSUE THREAD

**Issue by romgrk** [iamakulov/devtools-perf-tricks#1]
By any chance, do you know if the invalidation tracking is still working in recent versions of chrome? I've been trying to make the feature work without success.

**Comment by iamakulov** [comment]
Hmm – haven’t used it for some time tbh!

I do know Microsoft Edge includes it by default if you enable “Advanced Paint Instrumentation”, plus you can collect that data from chrome://tracing as well: https://twitter.com/iamakulov/status/1585656406170025986

**Comment by romgrk** [comment]
Thanks for the reply. It doesn't seem to work on the current chrome version (neither did it for any of my colleagues), but it did work on a chromium build from source using the latest commit, so I guess it's going to be fixed in newer versions.
